### ISSUE TITLE
route /test hyperscript error

### ISSUE THREAD

**Issue by bloodyKnuckles** [openskie/openskie#1]
see route /test, when passing a hyperscript object, having a list of hyperscript objects, an error occurs:

This works: `h('div', h('h1', 'test'))`
But this errors: `h('div', h('h1', 'test'), h('h2', 'test2'))`

/Users/.../openskie/node_modules/virtual-dom/node_modules/global/node_modules/min-document/serialize.js:117
        .replace(/&/g, "&amp;")
         ^
TypeError: undefined is not a function
at escapeText (/Users/.../openskie/node_modules/virtual-dom/node_modules/global/node_modules/min-document/serialize.js:117:10)
at escapeAttributeValue (../serialize.js:123:12)
at .../serialize.js:87:45
at Array.forEach (native)
at stringify (.../serialize.js:79:10)
at properties (.../serialize.js:112:27)
at serializeElement (.../serialize.js:25:34)
at serializeNode (.../serialize.js:12:20)
at DOMElement._Element_toString as toString (.../min-document/dom-element.js:155:12)
at Server.handle (/Users/.../openskie/index.js:27:36)

**Comment by bloodyKnuckles** [comment]
Children hyperscript objects need to be listed in an array:

h('div', [ h('h1', 'test'), h('h2', 'test2') ] )
